### ISSUE TITLE
Prism + Visual Studio 2017 for MacOS

### ISSUE THREAD

**Issue by rickybell** [angelobelchior/prism-xamarin-forms#10]
Olá.

Como instalo o Prism no Visual Studio 2017 no Mac.
Eu baixei o arquivo do vsix, mas não consegui instalar.

Obrigado.

**Comment by angelobelchior** [comment]
O arquivo *.vsix só funciona no Visual Studio para Windows. Ainda não existe previsão para o Prism Template Pack dar suporte ao VS for Mac. De qualquer maneira, você pode instalar as bibliotecas manualmente. Dá mais trabalho, mas não impede de usar o framework. :)

**Comment by rickybell** [comment]
Obrigado Angelo.



Henrique Bock Belloube
(11) 98801-9799/3876-0628
www.bex-web.com.br

From: Angelo Luis Rodrigues Da Silva <notifications@github.com>
<notifications@github.com>
Reply: angelobelchior/prism-xamarin-forms
<reply@reply.github.com>
<reply@reply.github.com>
Date: 26 de agosto de 2017 at 18:37:41
To: angelobelchior/prism-xamarin-forms
<prism-xamarin-forms@noreply.github.com>
<prism-xamarin-forms@noreply.github.com>
Cc: Henrique Bock Belloube <henrique.belloube@gmail.com>
<henrique.belloube@gmail.com>, Author <author@noreply.github.com>
<author@noreply.github.com>
Subject:  Re: [angelobelchior/prism-xamarin-forms] Prism + Visual Studio
2017 for MacOS (#10)

O arquivo *.vsix só funciona no Visual Studio para Windows. Ainda não
existe previsão para o Prism Template Pack dar suporte ao VS for Mac. De
qualquer maneira, você pode instalar as bibliotecas manualmente. Dá mais
trabalho, mas não impede de usar o framework. :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/angelobelchior/prism-xamarin-forms/issues/10#issuecomment-325163275>,
or mute the thread
